import PDFDocument from "pdfkit";

const WMO = {
  0: "Clear sky", 1: "Mainly clear", 2: "Partly cloudy", 3: "Overcast",
  45: "Fog", 48: "Rime fog", 51: "Light drizzle", 53: "Drizzle", 55: "Heavy drizzle",
  56: "Freezing drizzle", 57: "Freezing drizzle", 61: "Light rain", 63: "Rain", 65: "Heavy rain",
  66: "Freezing rain", 67: "Freezing rain", 71: "Light snow", 73: "Snow", 75: "Heavy snow",
  77: "Snow grains", 80: "Light showers", 81: "Showers", 82: "Violent showers",
  85: "Snow showers", 86: "Heavy snow showers", 95: "Thunderstorm",
  96: "Thunderstorm, hail", 99: "Thunderstorm, hail",
};

export function wmoLabel(code) {
  return WMO[code] ?? "—";
}

const tempU = (units) => (units === "imperial" ? "°F" : "°C");
const windU = (units) => (units === "imperial" ? "mph" : "km/h");
const precU = (units) => (units === "imperial" ? "in" : "mm");

function val(x) {
  return x === null || x === undefined ? "" : x;
}

/* ----------------------------------------------------------------- CSV */
export function toCSV(record) {
  const u = record.weather?.units ?? "metric";
  const header = [
    "date",
    "condition",
    `temp_max_${tempU(u)}`,
    `temp_min_${tempU(u)}`,
    `temp_mean_${tempU(u)}`,
    `precip_${precU(u)}`,
    `wind_max_${windU(u)}`,
    "sunrise",
    "sunset",
  ];
  const rows = (record.weather?.days ?? []).map((d) =>
    [
      d.date,
      `"${wmoLabel(d.weatherCode)}"`,
      val(d.tempMax),
      val(d.tempMin),
      val(d.tempMean),
      val(d.precipSum),
      val(d.windMax),
      val(d.sunrise),
      val(d.sunset),
    ].join(",")
  );
  return [header.join(","), ...rows].join("\n") + "\n";
}

/* ----------------------------------------------------------------- XML */
function esc(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function toXML(record) {
  const w = record.weather ?? {};
  const days = (w.days ?? [])
    .map(
      (d) => `    <day date="${esc(d.date)}">
      <condition>${esc(wmoLabel(d.weatherCode))}</condition>
      <weatherCode>${val(d.weatherCode)}</weatherCode>
      <tempMax>${val(d.tempMax)}</tempMax>
      <tempMin>${val(d.tempMin)}</tempMin>
      <tempMean>${val(d.tempMean)}</tempMean>
      <precipSum>${val(d.precipSum)}</precipSum>
      <windMax>${val(d.windMax)}</windMax>
      <sunrise>${esc(d.sunrise)}</sunrise>
      <sunset>${esc(d.sunset)}</sunset>
    </day>`
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<weatherQuery id="${record.id}">
  <location>
    <input>${esc(record.locationInput)}</input>
    <resolvedName>${esc(record.resolvedName)}</resolvedName>
    <region>${esc(record.region)}</region>
    <latitude>${val(record.latitude)}</latitude>
    <longitude>${val(record.longitude)}</longitude>
    <timezone>${esc(record.timezone)}</timezone>
  </location>
  <range start="${esc(record.startDate)}" end="${esc(record.endDate)}" source="${esc(record.source)}" units="${esc(w.units)}"/>
  <notes>${esc(record.notes)}</notes>
  <days>
${days}
  </days>
</weatherQuery>
`;
}

/* ------------------------------------------------------------- Markdown */
export function toMarkdown(record) {
  const w = record.weather ?? {};
  const u = w.units ?? "metric";
  const lines = [];
  lines.push(`# Weather report — ${record.resolvedName || record.locationInput}`);
  lines.push("");
  lines.push(`- **Location:** ${record.resolvedName || record.locationInput}${record.region ? ` (${record.region})` : ""}`);
  lines.push(`- **Coordinates:** ${record.latitude}, ${record.longitude}`);
  lines.push(`- **Date range:** ${record.startDate} → ${record.endDate}`);
  lines.push(`- **Data source:** Open-Meteo ${record.source === "archive" ? "(historical/ERA5)" : "(forecast)"}`);
  if (record.notes) lines.push(`- **Notes:** ${record.notes}`);
  lines.push("");

  const wiki = record.extras?.wikipedia;
  if (wiki?.extract) {
    lines.push(`## About ${wiki.title}`);
    lines.push("");
    lines.push(wiki.extract);
    if (wiki.url) lines.push(`\n[Wikipedia](${wiki.url})`);
    lines.push("");
  }

  lines.push(`## Daily weather`);
  lines.push("");
  lines.push(
    `| Date | Condition | High (${tempU(u)}) | Low (${tempU(u)}) | Precip (${precU(u)}) | Wind (${windU(u)}) |`
  );
  lines.push(`| --- | --- | ---: | ---: | ---: | ---: |`);
  for (const d of w.days ?? []) {
    lines.push(
      `| ${d.date} | ${wmoLabel(d.weatherCode)} | ${val(d.tempMax)} | ${val(d.tempMin)} | ${val(d.precipSum)} | ${val(d.windMax)} |`
    );
  }
  lines.push("");
  const aqi = record.extras?.airQuality;
  if (aqi?.usAqi != null) {
    lines.push(`_Current air quality (US AQI): ${aqi.usAqi}_`);
    lines.push("");
  }
  lines.push(`<sub>Generated by Weather Suite backend · data © Open-Meteo</sub>`);
  return lines.join("\n") + "\n";
}

/* ----------------------------------------------------------------- PDF */
/** Stream a PDF of the record to an Express response. */
export function streamPDF(record, res) {
  const w = record.weather ?? {};
  const u = w.units ?? "metric";
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  doc.pipe(res);

  doc.font("Helvetica-Bold").fontSize(22).fillColor("#13233b")
    .text(`Weather Report`, { continued: false });
  doc.moveDown(0.2);
  doc.font("Helvetica-Bold").fontSize(15).fillColor("#3e6ea8")
    .text(record.resolvedName || record.locationInput);
  doc.moveDown(0.6);

  doc.font("Helvetica").fontSize(10).fillColor("#444");
  const meta = [
    record.region ? `Region: ${record.region}` : null,
    `Coordinates: ${record.latitude}, ${record.longitude}`,
    `Range: ${record.startDate} to ${record.endDate}`,
    `Source: Open-Meteo ${record.source === "archive" ? "(historical)" : "(forecast)"}`,
    record.notes ? `Notes: ${record.notes}` : null,
  ].filter(Boolean);
  meta.forEach((line) => doc.text(line));
  doc.moveDown(0.6);

  const wiki = record.extras?.wikipedia;
  if (wiki?.extract) {
    doc.font("Helvetica-Bold").fontSize(12).fillColor("#13233b").text(`About ${wiki.title}`);
    doc.moveDown(0.2);
    doc.font("Helvetica").fontSize(10).fillColor("#333").text(wiki.extract, { align: "left" });
    doc.moveDown(0.8);
  }

  // Daily table
  doc.font("Helvetica-Bold").fontSize(12).fillColor("#13233b").text("Daily weather");
  doc.moveDown(0.4);

  const cols = [
    { key: "date", label: "Date", w: 80 },
    { key: "cond", label: "Condition", w: 150 },
    { key: "hi", label: `High ${tempU(u)}`, w: 70 },
    { key: "lo", label: `Low ${tempU(u)}`, w: 70 },
    { key: "pr", label: `Precip ${precU(u)}`, w: 70 },
  ];
  const startX = doc.x;
  let y = doc.y;

  function row(cells, bold) {
    doc.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(9).fillColor(bold ? "#13233b" : "#333");
    let x = startX;
    cols.forEach((c) => {
      doc.text(String(cells[c.key] ?? ""), x, y, { width: c.w, ellipsis: true });
      x += c.w;
    });
    y += 16;
    if (y > doc.page.height - 60) {
      doc.addPage();
      y = doc.y;
    }
  }

  row({ date: "Date", cond: "Condition", hi: `High ${tempU(u)}`, lo: `Low ${tempU(u)}`, pr: `Precip ${precU(u)}` }, true);
  doc.moveTo(startX, y - 3).lineTo(startX + 440, y - 3).strokeColor("#ccc").stroke();
  for (const d of w.days ?? []) {
    row({
      date: d.date,
      cond: wmoLabel(d.weatherCode),
      hi: val(d.tempMax),
      lo: val(d.tempMin),
      pr: val(d.precipSum),
    });
  }

  doc.moveDown(2);
  doc.font("Helvetica-Oblique").fontSize(8).fillColor("#888")
    .text("Generated by Weather Suite backend · data © Open-Meteo", startX, doc.page.height - 55);

  doc.end();
}

export const FORMATS = {
  json: { ext: "json", type: "application/json" },
  csv: { ext: "csv", type: "text/csv" },
  xml: { ext: "xml", type: "application/xml" },
  md: { ext: "md", type: "text/markdown" },
  markdown: { ext: "md", type: "text/markdown" },
  pdf: { ext: "pdf", type: "application/pdf" },
};
